# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixed_2group0 <- function(nnt, nn, n, k1, k2, k, a, y, ss, sigy, sig1) {
    .Call('_fastNoNo_mixed_2group0', PACKAGE = 'fastNoNo', nnt, nn, n, k1, k2, k, a, y, ss, sigy, sig1)
}

