# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_fastNoNo_rcppeigen_hello_world', PACKAGE = 'fastNoNo')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_fastNoNo_rcppeigen_outerproduct', PACKAGE = 'fastNoNo', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_fastNoNo_rcppeigen_innerproduct', PACKAGE = 'fastNoNo', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_fastNoNo_rcppeigen_bothproducts', PACKAGE = 'fastNoNo', x)
}

mixed_2group <- function(nnt, nn, n, k1, k2, k, a, y, ss, sigy, sig1, dsums, dsum, stds, dsums_cov) {
    invisible(.Call('_fastNoNo_mixed_2group', PACKAGE = 'fastNoNo', nnt, nn, n, k1, k2, k, a, y, ss, sigy, sig1, dsums, dsum, stds, dsums_cov))
}

